// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyItem(arg1) {
  return window['go']['app']['App']['CopyItem'](arg1);
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}
