// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clipboard} from '../models';
import {theme} from '../models';

export function CopyItem(arg1:string):Promise<void>;

export function GetHistory():Promise<Array<clipboard.ClipboardEntry>>;

export function GetTheme():Promise<theme.ThemeColors>;
